services:
  - type: web
    name: arabic-text-generator
    env: python
    buildCommand: npm install && npm run build:css && pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
    healthCheckPath: /
